version: 2.1
jobs:
  sonarqube-scan:
    docker:
      - image: sonarsource/sonar-scanner-cli:latest
    environment:
      SONAR_USER_HOME: "${CIRCLE_WORKING_DIRECTORY}/.sonar"
      GIT_DEPTH: "0"
      SONAR_TOKEN: ${SONAR_TOKEN}
      SONAR_HOST_URL: ${SONAR_HOST_URL}
      SONAR_PROJECT_KEY: ${SONAR_PROJECT_KEY}
    steps:
      - checkout
      - run:
          name: Run SonarQube Scanner
          command: |
            sonar-scanner \
              -Dsonar.qualitygate.wait=true \
              -Dsonar.host.url=$SONAR_HOST_URL \
              -Dsonar.projectKey=$SONAR_PROJECT_KEY \
              -Dsonar.token=$SONAR_TOKEN \
              -Dsonar.sources=.
  accuknox-sast-scan:
    docker:
      - image: cimg/base:current
    working_directory: /app/data/
    environment:
      SONAR_TOKEN: ${SONAR_TOKEN}
      SONAR_HOST_URL: ${SONAR_HOST_URL}
      SONAR_PROJECT_KEY: ${SONAR_PROJECT_KEY}
      REPORT_PATH: /app/data/
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: SAST Scan 
          command: |
            python3 sq-job.py
      - run:
          name: Uploading Results
          command: |
            for file in `ls -1 SQ-*.json`; do
              curl --location --request POST "https://${ACCUKNOX_ENDPOINT}/api/v1/artifact/?tenant_id=${ACCUKNOX_TENANT}&data_type=SQ&label_id=${ACCUKNOX_LABEL}&save_to_s3=false" --header "Tenant-Id: ${ACCUKNOX_TENANT}" --header "Authorization: Bearer ${ACCUKNOX_TOKEN}" --form "file=@\"$file\""
            done
workflows:
  accuknox-sast-scan:
    jobs:
      - sonarqube-scan:
          filters:
            branches:
              only:
              - sast
      - accuknox-sast-scan:
          requires:
            - sonarqube-scan
          filters:
            branches:
              only:
              - sast