version: 2.1
orbs:
  accuknox-scan: accuknox-scan/accuknox-test-scan@0.0.1
jobs:
  test:
    docker:
      - image: 'circleci/python:3.7.4'
    steps:
    - checkout
    - accuknox-scan/container-scan: 
        ACCUKNOX_TOKEN: ${ACCUKNOX_ENDPOINT}
        ACCUKNOX_TENANT: ${ACCUKNOX_TENANT}
        ACCUKNOX_ENDPOINT: ${ACCUKNOX_ENDPOINT}
        ACCUKNOX_LABEL: ${ACCUKNOX_LABEL}
workflows:
  test:
    jobs:
      - test:
          context: accuknox-scan