version: 2.1
jobs:
  sonarqube-scan:
    docker:
      - image: sonarsource/sonar-scanner-cli:latest
    environment:
      GIT_DEPTH: "0"
    steps:
      - checkout
      - run:
          name: test 
          command: |
            printenv
      - run:
          name: Run SonarQube Scanner
          command: |
            sonar-scanner \
              -Dsonar.qualitygate.wait=false \
              -Dsonar.host.url=$SONAR_HOST_URL \
              -Dsonar.projectKey=$SONAR_PROJECT_KEY \
              -Dsonar.token=$SONAR_TOKEN \
              -Dsonar.sources=.
  accuknox-sast:
    docker:
      - image: accuknox/sastjob:latest
    working_directory: /app/data/
    environment:
      REPORT_PATH: /app/data/
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: SAST 
          command: |
            SQ_URL=${SONAR_HOST_URL}
            SQ_AUTH_TOKEN=${SONAR_TOKEN}
            SQ_PROJECTS=${SONAR_PROJECT_KEY}
            python3 /app/sq-job.py
      - run:
          name: Uploading Results
          command: |
            for file in `ls -1 SQ-*.json`; do
              curl --location --request POST "https://${ACCUKNOX_ENDPOINT}/api/v1/artifact/?tenant_id=${ACCUKNOX_TENANT}&data_type=SQ&label_id=${ACCUKNOX_LABEL}&save_to_s3=false" --header "Tenant-Id: ${ACCUKNOX_TENANT}" --header "Authorization: Bearer ${ACCUKNOX_TOKEN}" --form "file=@\"$file\""
            done
workflows:
  accuknox-sast:
    jobs:
      # - sonarqube-scan:
      #     filters:
      #       branches:
      #         only:
      #         - sast
      - accuknox-sast:
          # requires:
          #   - sonarqube-scan
          filters:
            branches:
              only:
              - sast