version: 2.1
orbs:
  accuknox-scan: accuknox-scan/accuknox-test-scan@dev:1.37
workflows:
  accuknox:
    jobs:
      - accuknox-scan/dast:
          INPUT_SOFT_FAIL: false
          TARGET_URL: "http://testhtml5.vulnweb.com"