version: 2.1
orbs:
  accuknox-scan: accuknox-scan/accuknox-test-scan@dev:1.26
workflows:
  accuknox:
    jobs:
      - accuknox-scan/iac:
          INPUT_DIRECTORY: "./"
          INPUT_COMPACT: true
          INPUT_QUIET: true
          INPUT_SOFT_FAIL: true