version: 2.1
jobs:
  container-scan:
    working_directory: ./
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Download Scanner
          command: |
            curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin
      - run:
          name: Build Docker image
          command: |
            IMAGE_NAME=circleci-container-scan:$CIRCLE_BUILD_NUM
            docker build -t $IMAGE_NAME -f Dockerfile .
            echo "export IMAGE_NAME=$IMAGE_NAME" >> $BASH_ENV
      - run:
          name: Scan Docker image
          command: |
            set +e  # Allow commands to fail without stopping the script
            trivy image --exit-code 1 --severity "UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL" -f json $IMAGE_NAME -o results.json --quiet
            TRIVY_EXIT_CODE=$?
            echo "export TRIVY_EXIT_CODE=$TRIVY_EXIT_CODE" >> $BASH_ENV
      - run:
          name: Uploading Results
          command: |
            curl --location --request POST "https://${ACCUKNOX_ENDPOINT}/api/v1/artifact/?tenant_id=${ACCUKNOX_TENANT}&data_type=TR&label_id=${ACCUKNOX_LABEL}&save_to_s3=false" --header "Tenant-Id: ${ACCUKNOX_TENANT}" --header "Authorization: Bearer ${ACCUKNOX_TOKEN}" --form 'file=@"results.json"'
      - run:
          name: Failing Pipeline If Scan Failed
          command: |
            if [ "$TRIVY_EXIT_CODE" -ne 0 ]; then
              echo "Scan failed. Exiting with failure."
              exit 1
            fi
workflows:
  accuknox-container-scan:
    jobs:
      - container-scan:
          filters:
            branches:
              only:
              - container