version: 2.1

jobs:
  say-hello:
    docker:
      - image: accuknox/aspmscanner:v0.8.3
    steps:
      - checkout

      - run:
          name: Print Hello World
          command: echo "Hello, World!"

      - run:
          name: Show Last Commit ID and Message
          command: |
            echo "Last Commit ID:"
            git log -1 --pretty=format:'%H'
            echo ""
            echo "Last Commit Message:"
            git log -1 --pretty=format:'%s'

      - run:
          name: Show Directory Path
          command: pwd

      - run:
          name: List Files
          command: ls -la

workflows:
  hello-workflow:
    jobs:
      - say-hello
