version: 2.1
jobs:
  dast-scan:
    docker:
      - image: zaproxy/zap-stable:latest
    environment:
      TARGET_URL: "http://testhtml5.vulnweb.com"
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: DAST Scan 
          command: |
            mkdir -p /zap/wrk
            zap-baseline.py -t "$TARGET_URL" -J report.json -I
      - run:
          name: Uploading Results
          command: |
            curl --location --request POST "https://${ACCUKNOX_ENDPOINT}/api/v1/artifact/?tenant_id=${ACCUKNOX_TENANT}&data_type=ZAP&label_id=${ACCUKNOX_LABEL}&save_to_s3=false" --header "Tenant-Id: ${ACCUKNOX_TENANT}" --header "Authorization: Bearer ${ACCUKNOX_TOKEN}" --form 'file=@"report.json"'
workflows:
  accuknox-dast-scan:
    jobs:
      - dast-scan:
          filters:
            branches:
              only:
              - dast