name: AccuKnox Container Scan

on:
  push:
    branches:
      - container

jobs:
  accuknox-cicd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Pull and tag Node image
        run: |
          docker pull node:slim
          docker tag node:slim my-node-scan:latest

      - name: AccuKnox Container Scan
        uses: accuknox/container-scan-action@8c254eb7aa789ed8fd3c123c379b12fe17c2a49c
        with:
          token: ${{ secrets.ACCUKNOX_TOKEN }}
          tenant_id: 3730
          endpoint: "cspm.demo.accuknox.com"
          label: "SPOC"
          image: my-node-scan
          tag: latest
          severity: "CRITICAL"
