name: AccuKnox Container Scan

on:
  push:
    branches:
      - container

jobs:
  accuknox-cicd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: AccuKnox Container Scan
        uses: accuknox/container-scan-action@v1.0.0
        with:
          token: ${{ secrets.ACCUKNOX_TOKEN }}
          tenant_id: 3730
          endpoint: "cspm.demo.accuknox.com"
          repository_name: ${{ github.repository }}
          exit_code: 1
          dockerfile_context: Dockerfile