name: AccuKnox IaC Scan Workflow

on:
  push:
    branches:
      - iac-with-cli

jobs:
  clone-and-install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo (optional)
        uses: actions/checkout@v3

      - name: Install ASPM CLI with pip
        run: |
          # Recommended to releas on PyPI
          pip install https://github.com/accuknox/aspm-scanner-cli/releases/download/v0.1.0/accuknox_aspm_scanner-0.1.0-py3-none-any.whl

      - name: Run ASPM CLI scan
        env:
          ACCUKNOX_TENANT: 3730
          ACCUKNOX_LABEL: SPOC
          ACCUKNOX_ENDPOINT: cspm.demo.accuknox.com
          ACCUKNOX_TOKEN: ${{ secrets.ACCUKNOX_TOKEN }}
        run: |
            accuknox-aspm-scanner --softfail scan iac --quiet --compact