name: AccuKnox Container Scan

on:
  push:
    branches:
      - all

jobs:
  scan-container:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install ASPM Scanner CLI
        run: |
          pip install --break-system-packages https://github.com/accuknox/aspm-scanner-cli/releases/download/v0.8.14/accuknox_aspm_scanner-0.8.13-py3-none-any.whl

      - name: Run Container Scan
        run: |
          accuknox-aspm-scanner scan container --command "image nginx:latest --severity CRITICAL"
