name: AccuKnox Container Scan

on:
  push:
    branches:
      - all

jobs:
  scan-container:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: "Run Accuknox SAST"
      #   uses:  r3d-shadow/sast-scan-action@main
      #   with:
      #     sonar_token: ${{ secrets.SONAR_TOKEN }}
      #     sonar_host_url: "https://sq.accuknox.com"
      #     sonar_project_key: "spoc"
      #     accuknox_endpoint: "cspm.demo.accuknox.com"
      #     accuknox_token: ${{ secrets.ACCUKNOX_TOKEN }}
      #     tenant_id: 3730
      #     label: "SPOC"
      #     input_soft_fail: true
      #     skip_sonar_scan: false

      - name: "Run Accuknox SAST"
        uses:  r3d-shadow/sast-scan-action@main
        with:
          sonar_token: 123 ## ${{ secrets.SONAR_CLOUD_TOKEN }}
          sonar_host_url: "https://sonarcloud.io"
          sonar_project_key: "r3d-shadow_azure-plugin-test"
          sonar_organization_id: "r3d-shadow"
          accuknox_endpoint: "cspm.demo.accuknox.com"
          accuknox_token: 123 ## ${{ secrets.ACCUKNOX_TOKEN }}
          tenant_id: 3730
          label: "SPOC"
          input_soft_fail: false
          skip_sonar_scan: false