name: AccuKnox Secret Scan Workflow

on:
  push:
    branches:
      - secret

jobs:
  accuknox-cicd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: AccuKnox Secret Scan
        uses: accuknox/secret-scan-action@v1.0.1
        with:
          token: ${{ secrets.ACCUKNOX_TOKEN }}
          tenant_id: 3730
          label: "SPOC"
          endpoint:  "cspm.demo.accuknox.com"
          fail: true
          use_extended_ruleset: false